"""独立只读市场监测域。"""

from trading_assistant.market_radar.capabilities import (
    CapabilityReport,
    CapabilityResult,
    run_capability_checks,
    write_capability_report,
)
from trading_assistant.market_radar.config import MarketRadarConfig, load_market_radar_config
from trading_assistant.market_radar.earnings import (
    EarningsCalendarEvent,
    EarningsMarketCoverage,
    EarningsRevisionAggregate,
    EarningsRevisionSnapshot,
    Fy1EarningsTrend,
    SectorEarningsRevision,
    calculate_earnings_revision_snapshot,
)
from trading_assistant.market_radar.eodhd_calendar import EodhdCalendarSource
from trading_assistant.market_radar.eodhd_components import EodhdIndexComponentsSource
from trading_assistant.market_radar.macro import (
    RiskAppetiteComponents,
    RiskAppetitePoint,
    RiskAppetiteSnapshot,
    calculate_risk_appetite_snapshot,
)
from trading_assistant.market_radar.membership import (
    CurrentMarketMember,
    CurrentMarketMembership,
    CurrentMarketMembershipSource,
    CurrentMarketSectorAssignment,
    CurrentMarketSectorClassification,
    CurrentMarketSectorClassificationSource,
)
from trading_assistant.market_radar.metrics import (
    BreadthMetric,
    CurrentBreadthSnapshot,
    MarketPriceMetrics,
    MetricValue,
    PriceBar,
    PriceCoverage,
    PriceRadarSnapshot,
    SectorPriceMetrics,
    StockPriceMetrics,
    calculate_current_breadth_snapshot,
    calculate_price_snapshot,
)
from trading_assistant.market_radar.prices import (
    build_macro_price_instrument_specs,
    build_membership_instrument_specs,
    build_price_instrument_specs,
    load_internal_price_bars,
)
from trading_assistant.market_radar.service import (
    MarketBreadthSyncMode,
    MarketBreadthSyncSummary,
    MarketEarningsSyncSummary,
    MarketMacroSyncSummary,
    MarketRadarPriceSyncSummary,
    MarketRadarSyncMode,
    sync_current_market_breadth,
    sync_market_earnings,
    sync_market_macro,
    sync_market_radar_prices,
)
from trading_assistant.market_radar.storage import MarketRadarRepository, MarketRadarSyncRun

__all__ = [
    "BreadthMetric",
    "CapabilityReport",
    "CapabilityResult",
    "CurrentBreadthSnapshot",
    "CurrentMarketMember",
    "CurrentMarketMembership",
    "CurrentMarketMembershipSource",
    "CurrentMarketSectorAssignment",
    "CurrentMarketSectorClassification",
    "CurrentMarketSectorClassificationSource",
    "EarningsCalendarEvent",
    "EarningsMarketCoverage",
    "EarningsRevisionAggregate",
    "EarningsRevisionSnapshot",
    "EodhdCalendarSource",
    "EodhdIndexComponentsSource",
    "Fy1EarningsTrend",
    "MarketBreadthSyncMode",
    "MarketBreadthSyncSummary",
    "MarketEarningsSyncSummary",
    "MarketMacroSyncSummary",
    "MarketPriceMetrics",
    "MarketRadarConfig",
    "MarketRadarPriceSyncSummary",
    "MarketRadarRepository",
    "MarketRadarSyncMode",
    "MarketRadarSyncRun",
    "MetricValue",
    "PriceBar",
    "PriceCoverage",
    "PriceRadarSnapshot",
    "RiskAppetiteComponents",
    "RiskAppetitePoint",
    "RiskAppetiteSnapshot",
    "SectorEarningsRevision",
    "SectorPriceMetrics",
    "StockPriceMetrics",
    "build_macro_price_instrument_specs",
    "build_membership_instrument_specs",
    "build_price_instrument_specs",
    "calculate_current_breadth_snapshot",
    "calculate_earnings_revision_snapshot",
    "calculate_price_snapshot",
    "calculate_risk_appetite_snapshot",
    "load_internal_price_bars",
    "load_market_radar_config",
    "run_capability_checks",
    "sync_current_market_breadth",
    "sync_market_earnings",
    "sync_market_macro",
    "sync_market_radar_prices",
    "write_capability_report",
]
