/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Backtests
         * @description 分页返回回测审计状态和报告摘要。
         */
        get: operations["listBacktests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest
         * @description 返回回测摘要和可用报告表。
         */
        get: operations["getBacktest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Account
         * @description 分页返回回测账户报告。
         */
        get: operations["getBacktestAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Equity
         * @description 分页返回回测权益与收益曲线。
         */
        get: operations["getBacktestEquity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Fills
         * @description 分页返回回测成交报告。
         */
        get: operations["getBacktestFills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Orders
         * @description 分页返回回测订单报告。
         */
        get: operations["getBacktestOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Positions
         * @description 分页返回回测持仓报告。
         */
        get: operations["getBacktestPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog Coverage
         * @description 返回配置股票池的 signal/execution 日线覆盖。
         */
        get: operations["getCatalogCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/quality/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Data Quality
         * @description 返回最近一次数据质量检查。
         */
        get: operations["getLatestDataQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factors/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Factor
         * @description 返回最近一个完整因子批次。
         */
        get: operations["getLatestFactor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fills
         * @description 分页返回 paper 逐笔成交。
         */
        get: operations["listFills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description 返回 Web API 进程级存活状态。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-radar/breadth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Breadth
         * @description 返回最近完整运行发布的 SPY 当前持仓代理宽度。
         */
        get: operations["getMarketRadarBreadth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-radar/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sectors
         * @description 返回最近完整快照中的板块相对强弱。
         */
        get: operations["listMarketRadarSectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-radar/sectors/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector
         * @description 返回完整快照白名单中的一个板块。
         */
        get: operations["getMarketRadarSector"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-radar/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stocks
         * @description 筛选、排序并分页返回 watchlist 的价格趋势与风险。
         */
        get: operations["listMarketRadarStocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-radar/stocks/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock
         * @description 返回完整快照白名单中的一个 watchlist 标的。
         */
        get: operations["getMarketRadarStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market-radar/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description 返回最近完整价格快照和六个雷达能力状态。
         */
        get: operations["getMarketRadarSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orders
         * @description 按订单标识聚合并分页返回生命周期摘要。
         */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{client_order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Order
         * @description 返回一个订单的全部审计事件与成交。
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview
         * @description 返回操作总览首屏所需的只读汇总。
         */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description 返回最近一次完整账户和持仓快照。
         */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Portfolio History
         * @description 分页返回账户资金快照历史。
         */
        get: operations["listPortfolioHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Signals
         * @description 分页筛选逐标的信号。
         */
        get: operations["listSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Strategy
         * @description 返回活动策略和统一风控阈值。
         */
        get: operations["getActiveStrategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description 返回 Web 能直接证明的数据源和运行时状态。
         */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description 分页筛选信号审批与执行工作流。
         */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow
         * @description 返回一个信号从产生到成交的审计时间线。
         */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountHistoryPageResponse */
        AccountHistoryPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["AccountHistoryPointResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AccountHistoryPointResponse */
        AccountHistoryPointResponse: {
            /** Account Id */
            account_id: string;
            /** Currency */
            currency: string;
            /** Free Cash */
            free_cash: number;
            /** Locked Cash */
            locked_cash: number;
            /** Net Liquidation */
            net_liquidation: number;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
        };
        /** BacktestDetailResponse */
        BacktestDetailResponse: {
            /** Available Tables */
            available_tables: string[];
            run: components["schemas"]["BacktestRunResponse"];
            /** Summary */
            summary: {
                [key: string]: string | number | boolean | null;
            };
        };
        /** BacktestPageResponse */
        BacktestPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["BacktestRunResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** BacktestRunResponse */
        BacktestRunResponse: {
            /** Annualized Return */
            annualized_return: number | null;
            /** Completed At Utc */
            completed_at_utc: string | null;
            /** End */
            end: string | null;
            /** Evaluation Start */
            evaluation_start: string | null;
            /** Final Equity Usd */
            final_equity_usd: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /**
             * Report State
             * @enum {string}
             */
            report_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
            /** Run Id */
            run_id: string;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Started At Utc */
            started_at_utc: string | null;
            /** Status */
            status: string;
            /** Strategy Name */
            strategy_name: string | null;
        };
        /** BreadthMetricResponse */
        BreadthMetricResponse: {
            coverage: components["schemas"]["RadarCoverageResponse"];
            /** History Required */
            history_required: number;
            /**
             * Validity
             * @enum {string}
             */
            validity: "complete" | "partial" | "insufficient_coverage";
            /** Value */
            value: number | null;
        };
        /** CatalogCoverageResponse */
        CatalogCoverageResponse: {
            /** Bar Type */
            bar_type: string;
            /** First At Utc */
            first_at_utc: string | null;
            /** Instrument Id */
            instrument_id: string;
            /** Last At Utc */
            last_at_utc: string | null;
            /**
             * Price Kind
             * @enum {string}
             */
            price_kind: "signal" | "execution";
            /**
             * State
             * @enum {string}
             */
            state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
            /** Symbol */
            symbol: string;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** Coverage */
            coverage: components["schemas"]["CatalogCoverageResponse"][];
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Provider */
            provider: string;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** DataQualityResponse */
        DataQualityResponse: {
            /** Bars Fetched */
            bars_fetched: number;
            /** Bars Written */
            bars_written: number;
            /** Corporate Actions Written */
            corporate_actions_written: number;
            /** Error Count */
            error_count: number;
            /** Generated At Utc */
            generated_at_utc: string | null;
            /** Instruments */
            instruments: components["schemas"]["QualityInstrumentResponse"][];
            /** Issues */
            issues: components["schemas"]["QualityIssueResponse"][];
            /** Mode */
            mode: string | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
            /** Warning Count */
            warning_count: number;
        };
        /** DecisionResponse */
        DecisionResponse: {
            /** Approval Mode */
            approval_mode: string;
            /** Decision */
            decision: string;
            /** Event Id */
            event_id: string;
            /** Reason */
            reason: string;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
        };
        /** FactorScoreResponse */
        FactorScoreResponse: {
            /** Canonical Id */
            canonical_id: string;
            /** Eligible */
            eligible: boolean;
            /** Rank */
            rank: number | null;
            /** Score */
            score: number;
            /** Security Id */
            security_id: string;
            /** Selected */
            selected: boolean;
            /** Symbol */
            symbol: string;
            /** Target Weight */
            target_weight: number;
        };
        /** FactorSnapshotResponse */
        FactorSnapshotResponse: {
            /** Asof Date */
            asof_date: string | null;
            /** Available At Utc */
            available_at_utc: string | null;
            /** Batch Id */
            batch_id: string | null;
            /** Delivery Id */
            delivery_id: string | null;
            /** Expected Rows */
            expected_rows: number;
            /** Model Release Id */
            model_release_id: string | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Scores */
            scores: components["schemas"]["FactorScoreResponse"][];
            /** Source Kind */
            source_kind: string | null;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** FillPageResponse */
        FillPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["FillResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** FillResponse */
        FillResponse: {
            /** Client Order Id */
            client_order_id: string;
            /** Commission */
            commission: number;
            /** Direction */
            direction: string;
            /** Event Id */
            event_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
            /** Trade Id */
            trade_id: string;
        };
        /**
         * HealthResponse
         * @description 进程级健康状态。
         */
        HealthResponse: {
            /**
             * Checked At Utc
             * Format: date-time
             */
            checked_at_utc: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MarketBreadthResponse */
        MarketBreadthResponse: {
            ad10: components["schemas"]["BreadthMetricResponse"] | null;
            /** As Of Date */
            as_of_date: string | null;
            b200: components["schemas"]["BreadthMetricResponse"] | null;
            b50: components["schemas"]["BreadthMetricResponse"] | null;
            /** Calculated At Utc */
            calculated_at_utc: string | null;
            freshness: components["schemas"]["RadarFreshnessResponse"] | null;
            /** Membership Date */
            membership_date: string | null;
            /** Membership Source */
            membership_source: string | null;
            nhnl: components["schemas"]["BreadthMetricResponse"] | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
            /**
             * Validity
             * @enum {string}
             */
            validity: "complete" | "partial" | "stale" | "insufficient_coverage" | "unavailable";
        };
        /** MarketRadarSummaryResponse */
        MarketRadarSummaryResponse: {
            /** As Of Date */
            as_of_date: string | null;
            /** Calculated At Utc */
            calculated_at_utc: string | null;
            coverage: components["schemas"]["RadarCoverageResponse"] | null;
            market: components["schemas"]["RadarMarketResponse"] | null;
            /** Modules */
            modules: components["schemas"]["RadarModuleResponse"][];
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** OrderDetailResponse */
        OrderDetailResponse: {
            /** Events */
            events: components["schemas"]["OrderEventResponse"][];
            /** Fills */
            fills: components["schemas"]["FillResponse"][];
            summary: components["schemas"]["OrderSummaryResponse"];
        };
        /** OrderEventResponse */
        OrderEventResponse: {
            /** Client Order Id */
            client_order_id: string;
            /** Direction */
            direction: string;
            /** Event Id */
            event_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
        };
        /** OrderPageResponse */
        OrderPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["OrderSummaryResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** OrderSummaryResponse */
        OrderSummaryResponse: {
            /** Client Order Id */
            client_order_id: string;
            /** Direction */
            direction: string;
            /** Event Count */
            event_count: number;
            /** Event Id */
            event_id: string;
            /** Fill Count */
            fill_count: number;
            /** Filled Quantity */
            filled_quantity: number;
            /**
             * First Event At Utc
             * Format: date-time
             */
            first_event_at_utc: string;
            /** Instrument Id */
            instrument_id: string;
            /**
             * Latest Event At Utc
             * Format: date-time
             */
            latest_event_at_utc: string;
            /** Quantity */
            quantity: number;
            /** Status */
            status: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            active_strategy: components["schemas"]["StrategyResponse"];
            /**
             * Data Quality State
             * @enum {string}
             */
            data_quality_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
            latest_factor: components["schemas"]["FactorSnapshotResponse"];
            /** Latest Fill At Utc */
            latest_fill_at_utc: string | null;
            /** Latest Workflow At Utc */
            latest_workflow_at_utc: string | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            portfolio: components["schemas"]["PortfolioResponse"];
            /** Workflow Status Counts */
            workflow_status_counts: {
                [key: string]: number;
            };
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Account Id */
            account_id: string | null;
            /** Age Seconds */
            age_seconds: number | null;
            /** Currency */
            currency: string | null;
            /** Free Cash */
            free_cash: number | null;
            /** Is Stale */
            is_stale: boolean | null;
            /** Locked Cash */
            locked_cash: number | null;
            /** Net Liquidation */
            net_liquidation: number | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Positions */
            positions: components["schemas"]["PositionResponse"][];
            /** Snapshot At Utc */
            snapshot_at_utc: string | null;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** PositionResponse */
        PositionResponse: {
            /** Avg Open Price */
            avg_open_price: number;
            /** Canonical Id */
            canonical_id: string;
            /** Estimated Market Value */
            estimated_market_value: number | null;
            /** Estimated Weight */
            estimated_weight: number | null;
            /** Price Kind */
            price_kind: string | null;
            /** Realized Pnl */
            realized_pnl: number | null;
            /** Reference Price */
            reference_price: number | null;
            /** Reference Price At Utc */
            reference_price_at_utc: string | null;
            /** Side */
            side: string;
            /** Signed Quantity */
            signed_quantity: number;
            /** Source Instrument Id */
            source_instrument_id: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * ProblemResponse
         * @description 统一错误响应。
         */
        ProblemResponse: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Title */
            title: string;
        };
        /** QualityInstrumentResponse */
        QualityInstrumentResponse: {
            /** Bar Count */
            bar_count: number;
            /** First At Utc */
            first_at_utc: string | null;
            /** Instrument Id */
            instrument_id: string;
            /** Issue Count */
            issue_count: number;
            /** Last At Utc */
            last_at_utc: string | null;
        };
        /** QualityIssueResponse */
        QualityIssueResponse: {
            /** Code */
            code: string;
            /** Instrument Id */
            instrument_id: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
            /** Timestamp Utc */
            timestamp_utc: string | null;
        };
        /** RadarCoverageResponse */
        RadarCoverageResponse: {
            /** Eligible */
            eligible: number;
            /** Observed */
            observed: number;
            /** Ratio */
            ratio: number;
        };
        /** RadarFreshnessResponse */
        RadarFreshnessResponse: {
            /** Membership Age Days */
            membership_age_days: number;
            /** Stale After Days */
            stale_after_days: number;
        };
        /** RadarMarketResponse */
        RadarMarketResponse: {
            rsp_spy_return_20: components["schemas"]["RadarMetricResponse"];
            spy_distance_ma_200: components["schemas"]["RadarMetricResponse"];
            spy_return_20: components["schemas"]["RadarMetricResponse"];
        };
        /** RadarMetricResponse */
        RadarMetricResponse: {
            /** Observations */
            observations: number;
            /** Required */
            required: number;
            /**
             * Validity
             * @enum {string}
             */
            validity: "complete" | "insufficient_history" | "unavailable";
            /** Value */
            value: number | null;
        };
        /** RadarModuleResponse */
        RadarModuleResponse: {
            /** Detail */
            detail: string;
            /** Label */
            label: string;
            /** Module Id */
            module_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "complete" | "partial" | "stale" | "insufficient_history" | "insufficient_coverage" | "unavailable";
        };
        /** ReportTableResponse */
        ReportTableResponse: {
            /** Columns */
            columns: string[];
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: string | number | boolean | null;
            }[];
        };
        /** SectorRadarListResponse */
        SectorRadarListResponse: {
            /** As Of Date */
            as_of_date: string | null;
            /** Calculated At Utc */
            calculated_at_utc: string | null;
            /** Items */
            items: components["schemas"]["SectorRadarResponse"][];
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** SectorRadarResponse */
        SectorRadarResponse: {
            /** Instrument Id */
            instrument_id: string;
            relative_strength_20: components["schemas"]["RadarMetricResponse"];
            relative_strength_60: components["schemas"]["RadarMetricResponse"];
            /** Sector Id */
            sector_id: string;
        };
        /** SignalPageResponse */
        SignalPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["SignalResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SignalResponse */
        SignalResponse: {
            /** Direction */
            direction: string;
            /** Event Id */
            event_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /** Strategy Name */
            strategy_name: string;
            /** Target Weight */
            target_weight: number;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
        };
        /** SourceStatusResponse */
        SourceStatusResponse: {
            /** Detail */
            detail: string;
            /** Last Event At Utc */
            last_event_at_utc: string | null;
            /** Name */
            name: string;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** StockRadarPageResponse */
        StockRadarPageResponse: {
            /** As Of Date */
            as_of_date: string | null;
            /** Calculated At Utc */
            calculated_at_utc: string | null;
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["StockRadarResponse"][];
            /** Limit */
            limit: number;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Offset */
            offset: number;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** StockRadarResponse */
        StockRadarResponse: {
            atr_20_ratio: components["schemas"]["RadarMetricResponse"];
            distance_ma_200: components["schemas"]["RadarMetricResponse"];
            /** Instrument Id */
            instrument_id: string;
            max_drawdown_126: components["schemas"]["RadarMetricResponse"];
            momentum_126_21: components["schemas"]["RadarMetricResponse"];
            realized_volatility_20: components["schemas"]["RadarMetricResponse"];
            /** Sector Id */
            sector_id: string;
            sector_relative_momentum_126_21: components["schemas"]["RadarMetricResponse"];
            /** Symbol */
            symbol: string;
        };
        /** StrategyResponse */
        StrategyResponse: {
            /** Approval Mode */
            approval_mode: string | null;
            /** Name */
            name: string | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Parameters */
            parameters: {
                [key: string]: string | number | boolean | null;
            };
            /** Risk Limits */
            risk_limits: {
                [key: string]: string | number | boolean | null;
            };
            /** Signal Expiry Hours */
            signal_expiry_hours: number | null;
            /**
             * Source State
             * @enum {string}
             */
            source_state: "available" | "empty" | "missing" | "invalid" | "unconfigured" | "unobserved";
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Sources */
            sources: components["schemas"]["SourceStatusResponse"][];
        };
        /** TimelineEventResponse */
        TimelineEventResponse: {
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "signal" | "decision" | "order" | "fill";
            /** Status */
            status: string;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
            /** Title */
            title: string;
        };
        /** WorkflowDetailResponse */
        WorkflowDetailResponse: {
            /** Decisions */
            decisions: components["schemas"]["DecisionResponse"][];
            /** Fills */
            fills: components["schemas"]["FillResponse"][];
            /** Orders */
            orders: components["schemas"]["OrderEventResponse"][];
            /** Planned Orders */
            planned_orders: {
                [key: string]: string | number | boolean | null;
            }[];
            /** Target Weights */
            target_weights: [
                string,
                number
            ][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEventResponse"][];
            workflow: components["schemas"]["WorkflowResponse"];
        };
        /** WorkflowPageResponse */
        WorkflowPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["WorkflowResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** WorkflowResponse */
        WorkflowResponse: {
            /** Event Id */
            event_id: string;
            /**
             * Expires At Utc
             * Format: date-time
             */
            expires_at_utc: string;
            /** Planned Order Count */
            planned_order_count: number;
            /** Reason */
            reason: string;
            /** Rebalance Key */
            rebalance_key: string;
            /** Risk Summary */
            risk_summary: string | null;
            /**
             * Signal Timestamp Utc
             * Format: date-time
             */
            signal_timestamp_utc: string;
            /** Status */
            status: string;
            /** Strategy Name */
            strategy_name: string;
            /** Target Count */
            target_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBacktests: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetailResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getBacktestAccount: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTableResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getBacktestEquity: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTableResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getBacktestFills: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTableResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getBacktestOrders: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTableResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getBacktestPositions: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTableResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getCatalogCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getLatestDataQuality: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getLatestFactor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorSnapshotResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listFills: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                instrument_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getMarketRadarBreadth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketBreadthResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listMarketRadarSectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorRadarListResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getMarketRadarSector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorRadarResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listMarketRadarStocks: {
        parameters: {
            query?: {
                sector?: string | null;
                query?: string | null;
                sort?: "instrument" | "momentum" | "relative_momentum" | "volatility" | "drawdown";
                direction?: "asc" | "desc";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockRadarPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getMarketRadarStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockRadarResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getMarketRadarSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketRadarSummaryResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                status?: string | null;
                instrument_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listPortfolioHistory: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountHistoryPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listSignals: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                status?: string | null;
                instrument_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getActiveStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowPageResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailResponse"];
                };
            };
            /** @description 查询对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 请求参数无效 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 只读数据源无法读取 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
}
